# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[prod]
[prod.global.parameters]
stack_name = "andylilfs-blog-backend-prod"
tags = { Environment = "prod", Project = "andylilfs-blog-backend" }

[prod.build.parameters]
cached = true
parallel = true

[prod.validate.parameters]
lint = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "andylilfs-blog-backend-prod"
region = "us-east-1"
image_repositories = []
parameter_overrides = "AWSENVNAME=\"AWS\""

[prod.package.parameters]
resolve_s3 = true

[prod.sync.parameters]
watch = true

[prod.local_start_api.parameters]
warm_containers = "EAGER"

[prod.local_start_lambda.parameters]
warm_containers = "EAGER"
