name: Deploy SAM Application

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy-sam:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set environment variables
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "CONFIG_FILE=samconfig-prod.toml" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=stg" >> $GITHUB_ENV
          echo "CONFIG_FILE=samconfig-stg.toml" >> $GITHUB_ENV
        fi

    - name: Build SAM application
      run: sam build --use-container

    - name: Deploy SAM application
      run: |
        sam deploy --config-file ${{ env.CONFIG_FILE }} --config-env ${{ env.ENVIRONMENT }} --no-confirm-changeset --no-fail-on-empty-changeset
